apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    volumeMounts:
    - name: nginx-logs
      mountPath: /var/log/nginx
    imagePullPolicy: Always

  - name: log-reader
    image: busybox:1.36
    command: ["/bin/sh"]
    args: ["-c", "tail -f /var/log/nginx/access.log"]
    volumeMounts:
    - name: nginx-logs
      mountPath: /var/log/nginx
    imagePullPolicy: Always

  volumes:
  - name: nginx-logs
    emptyDir: {}

